
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Adarsh Maurya
 */
public class Book_det extends javax.swing.JFrame {

    /**
     * Creates new form Author_det
     */
    estconnect ob=new estconnect();
    public Book_det() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnadd = new javax.swing.JButton();
        txtauthID = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        lblauthid = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        txtPID = new javax.swing.JTextField();
        lblPID = new javax.swing.JLabel();
        txtBID = new javax.swing.JTextField();
        lblBID = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("List of Books");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 50, 420, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BID", "AuthID", "PID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(70, 110, 610, 290);

        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd);
        btnadd.setBounds(590, 40, 100, 30);
        getContentPane().add(txtauthID);
        txtauthID.setBounds(170, 490, 80, 30);
        getContentPane().add(txtname);
        txtname.setBounds(440, 490, 220, 30);

        lblauthid.setText("AuthID");
        getContentPane().add(lblauthid);
        lblauthid.setBounds(170, 450, 80, 30);

        lblname.setText("Name");
        getContentPane().add(lblname);
        lblname.setBounds(440, 450, 170, 30);

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave);
        btnsave.setBounds(670, 420, 61, 25);
        getContentPane().add(txtPID);
        txtPID.setBounds(300, 490, 80, 30);

        lblPID.setText("PID");
        getContentPane().add(lblPID);
        lblPID.setBounds(300, 450, 80, 30);
        getContentPane().add(txtBID);
        txtBID.setBounds(70, 490, 80, 30);

        lblBID.setText("BID");
        getContentPane().add(lblBID);
        lblBID.setBounds(70, 450, 80, 30);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 20, 79, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        setedittrue();
    }//GEN-LAST:event_btnaddActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       seteditfalse();
        String code="select * from book_det;";
           ob.execute(code);
           DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
           model.setRowCount(0);
           String[] s=new String[4];
           try{
               while(ob.rs.next()){
                   s[0]=ob.rs.getString(1);
                   s[1]=ob.rs.getString(2);
                   s[2]=ob.rs.getString(3);
                   s[3]=ob.rs.getString(4);
                   model.addRow(s);
               }
           }
           catch(Exception e){
               System.out.println("error in getting data");
           }
    }//GEN-LAST:event_formWindowActivated

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
            String BID="",authid="", PID="",name="";
            BID=txtBID.getText();
        authid=txtauthID.getText();
        PID=txtPID.getText();
        name=txtname.getText();
        if(BID.length()==0||authid.length()==0||PID.length()==0||name.length()==0){
            JOptionPane.showMessageDialog(this,"Please enter every detail");
        }
        else{
            String sql="insert into book_det values('"+BID+"','"+authid+"','"+PID+"','"+name+"');";
            int flag=ob.update(sql);
        
        if(flag==1){
            JOptionPane.showMessageDialog(null,"record added successfully");
            new Publisher_det().setVisible(true);
            this.dispose();
         }
        else if(flag==0)
                JOptionPane.showMessageDialog(null,"record addition failed");
        seteditfalse();
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
   public void seteditfalse(){
        btnsave.setEnabled(false);
        lblauthid.setEnabled(false);
        lblPID.setEnabled(false);
        lblname.setEnabled(false);
        txtauthID.setEnabled(false);
        txtPID.setEnabled(false);
        txtname.setEnabled(false);
           lblBID.setEnabled(false);
        txtBID.setEnabled(false);
    }
   public void setedittrue(){
        btnsave.setEnabled(true);
        lblauthid.setEnabled(true);
        lblPID.setEnabled(true);
        lblname.setEnabled(true);
        txtauthID.setEnabled(true);
        txtPID.setEnabled(true);
        txtname.setEnabled(true);
        lblBID.setEnabled(true);
        txtBID.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Author_det.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Author_det.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Author_det.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Author_det.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Book_det().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBID;
    private javax.swing.JLabel lblPID;
    private javax.swing.JLabel lblauthid;
    private javax.swing.JLabel lblname;
    private javax.swing.JTextField txtBID;
    private javax.swing.JTextField txtPID;
    private javax.swing.JTextField txtauthID;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
